[[pages]]
path = "pages/main_page.py"
name = "Dashboard"
icon = "🚄"

[[pages]]
name = "Data Analysis"
icon = ""
is_section = true

[[pages]]
path = "pages/visual.py"
name = "Diagramme"
icon = ""

[[pages]]
path = "pages/stations.py"
name = "Verspätung nach Station"
icon = ""

[[pages]]
path = "pages/direct_connections.py"
name = "Verbindungs-Historie"
icon = ""

[[pages]]
name = "Machine Learning"
icon = ""
is_section = true

[[pages]]
path = "pages/predictor.py"
name = "Verspätungsprognose nach Zugnummer"
icon = ""

[[pages]]
path = "pages/best-train.py"
name = "Verspätungsprognose nach Strecke"
icon = ""



